use cebercol;
select * from barrios;
insert into barrios(nombre,codigo_comuna) values ("Arenal", 1),
("Buenos Aires", 1),
("Buenos Aires II", 1),
("Cardales", 1),
("Colombia", 1),
("David Nuñez Cala", 1),
("El Cruce", 1),
("El Dorado", 1),
("El Recreo", 1),
("Gonzalo Jiménez de Quesada", 1),
("Invasión San Luis", 1),
("Isla del Zapato", 1),
("La campana", 1),
("La Victoria", 1),
("La Victoria I", 1),
("Las Margaritas", 1),
("Las Playas", 1),
("Palmira", 1),
("San Francisco", 1),
("Sector Comercial Muelle", 1),
("Tres Unidos", 1),
("Urb. Nuevo Palmira", 1),
("Aguas Claras", 2),
("Ciudad Bolívar", 2),
("Galán Gómez", 2),
("Olaya Herrera", 2),
("Parnaso", 2),
("Barrio Pueblo Nuevo", 2),
("Barrio Torcoroma", 2),
("Barrio Uribe Uribe", 2),
("Barrio Villa Luz", 2),
("Algarrobos", 3),
("Alto De Los Ángeles", 3),
("Altos De La Virgen", 3),
("Altos Del Rosario", 3),
("Caminos De San Silvestre", 3),
("Brisas Del 20 De Enero", 3),
("Campo Hermoso", 3),
("Ciudadela Pipatón", 3),
("Colinas Del Norte", 3),
("Colinas Del Sur J.V.C.", 3),
("Cortijillo", 3),
("Cristo Rey", 3),
("Eduardo Rolón", 3),
("Internacional, 22 De Marzo", 3),
("Jerusalén", 3),
("Jorge Eliecer Gaitán", 3),
("La Castellana", 3),
("La Gran Vía", 3),
("La Libertad", 3),
("La Paz", 3),
("La Paz II", 3),
("Los Ficus J.V.C", 3),
("Luis Eleazar, Novalito J.V.C.", 3),
("Primero De Abril J.V.C.", 3),
("San Judas Tadeo", 3),
("Brisas De La Libertad", 3),
("Miradores Del Cacique", 3),
("Veinte De Enero", 3),
("Villa Maria Irida", 3),
("Villa Nueva", 3),
("Villas De Santa Isabel", 3),
("La Tora", 3),
("Las Camelias", 3),
("Altos Del Cincuentenario", 4),
("Altos Del Cañaveral", 4),
("Antonia Santos", 4),
("Cincuentenario", 4),
("Bellavista", 4),
("Bosques De La Cira", 4),
("Bosques De La Cira II", 4),
("Buenavista", 4),
("Buenavista II", 4),
("Cincuentenario", 4),
("Cincuentenario Vi", 4),
("Ciudadela Del Ctnario", 4),
("El Bosque", 4),
("El Castillo", 4),
("El Palmar", 4),
("El Refugio", 4),
("Nuevo Milenio Sur", 4),
("Villa Del Ctnario", 4),
("Jose Antonio Galán", 4),
("La Liga", 4),
("La Península", 4),
("Las Brisas", 4),
("Las Nieves", 4),
("Limonar", 4),
("Los Almendros", 4),
("Los Lagos", 4),
("Los Naranjos", 4),
("J.V.C. Los Nogales", 4),
("Los Pinos", 4),
("Marsella", 4),
("Miradores De La Ceiba", 4),
("Prados Del Cincuentenario", 4),
("Planada Del Cerro", 4),
("Santa Bárbara", 4),
("Tamarindos Club", 4),
("Urbanización 2000", 4),
("Villa Sandra", 4),
("Villa De Leyva", 4),
("Villa Olímpica", 4),
("Villa Rosa", 4),
("Yarima", 4),
("Los Mandarinos", 4),
("Alcázar", 5),
("Colinas Del Seminario", 5),
("La Nueva Esperanza", 5),
("Las Torres", 5),
("Nuevo Milenio", 5),
("Barrancabermeja", 5),
("Campo Alegre", 5),
("Chapinero", 5),
("El Chico", 5),
("El Porvenir", 5),
("El Triunfo", 5),
("Chapinero II", 5),
("J.V.C. Ramaral", 5),
("J.V.C. Tierradentro II", 5),
("La Candelaria", 5),
("La Esperanza", 5),
("La Independencia", 5),
("Las Mercedes", 5),
("La Tora", 5),
("Las Américas", 5),
("Las Camelias", 5),
("Las Malvinas Bajas", 5),
("Los Rosales", 5),
("Malvinas Alta", 5),
("Miraflores", 5),
("Primero De Mayo", 5),
("San Pedro Claver", 5),
("San José De Provivienda", 5),
("San José Obrero", 5),
("Santa Ana", 5),
("Santander", 5),
("Simon Bolívar", 5),
("Tierra Adentro", 5),
("Urbanización Los Lagos", 5),
("Versalles", 5),
("Villa Rosita", 5),
("Antonio Nariño", 6),
("Benjamin Herrera", 6),
("Boston", 6),
("Brisas de San Martin", 6),
("Brisas de Versalles", 6),
("Brisas del Oriente", 6),
("Corintos", 6),
("Danubio", 6),
("El Progreso", 6),
("Veinte de Agosto", 6),
("Kennedy", 6),
("Las Granjas", 6),
("Los Alamos", 6),
("Los Alpes", 6),
("Los Comuneros", 6),
("Oro Negro", 6),
("Puerta del Sol", 6),
("Rafael Rangel", 6),
("San Pedro", 6),
("Las Granjas", 6),
("Veinte de Agosto", 6),
("Veinte de Julio", 6),
("Villa del Coral", 6),
("Villa Fauda", 6),
("16 De Marzo", 7),
("9 De Abril", 7),
("Altos Del Campestre", 7),
("Las Palmas", 7),
("Villa Aura", 7),
("Campestre", 7),
("Colinas Del Campestre", 7),
("Divino Niño", 7),
("El Campin", 7),
("El Paraíso", 7),
("Las Flores", 7),
("Los Fundadores", 7),
("Maria Eugenia", 7),
("Minas Del Paraíso", 7),
("Nuevo Horizonte", 7),
("Pablo Acuña", 7),
("Prados Del Campestre", 7),
("Urbanización Los Corales", 7),
("Minas Del Paraíso", 7),
("Vereda La Independencia", 7),
("Villarelis Dos", 7),
("Villarelis Uno", 7),
("Villarelis Tres", 7);
