use cebercol;
select * from inmueble;
insert into inmueble(baños,habitaciones,patio,garaje,descripcion,tipo_inmueble,tipo_servicio,precio,codigo_arrendador) values ("2","3","si","no","ninguna","apartamento","1","900000","12");
insert into inmueble(baños,habitaciones,patio,garaje,descripcion,tipo_inmueble,tipo_servicio,precio,codigo_arrendador) values ("3","3","si","no","ninguna","apartamento","2","850000","13");
insert into inmueble(baños,habitaciones,patio,garaje,descripcion,tipo_inmueble,tipo_servicio,precio,codigo_arrendador) values ("4","3","si","si","ninguna","casa","1","1000000","14");
insert into inmueble(baños,habitaciones,patio,garaje,descripcion,tipo_inmueble,tipo_servicio,precio,codigo_arrendador) values ("2","4","si","no","ninguna","apartamento","2","950000","13");
insert into inmueble(baños,habitaciones,patio,garaje,descripcion,tipo_inmueble,tipo_servicio,precio,codigo_arrendador) values ("2","3","si","no","ninguna","casa","1","940000","15");
insert into inmueble(baños,habitaciones,patio,garaje,descripcion,tipo_inmueble,tipo_servicio,precio,codigo_arrendador) values ("2","3","si","no","ninguna","apartamento","2","960000","12");
insert into inmueble(baños,habitaciones,patio,garaje,descripcion,tipo_inmueble,tipo_servicio,precio,codigo_arrendador) values ("1","3","si","no","ninguna","apartamento","1","970000","12");
insert into inmueble(baños,habitaciones,patio,garaje,descripcion,tipo_inmueble,tipo_servicio,precio,codigo_arrendador) values ("1","1","si","no","ninguna","casa","1","600000","12");
insert into inmueble(baños,habitaciones,patio,garaje,descripcion,tipo_inmueble,tipo_servicio,precio,codigo_arrendador) values ("1","2","si","no","ninguna","apartamento","2","700000","12");
insert into inmueble(baños,habitaciones,patio,garaje,descripcion,tipo_inmueble,tipo_servicio,precio,codigo_arrendador) values ("2","1","si","si","ninguna","apartamento","1","670000","12");
insert into inmueble(baños,habitaciones,patio,garaje,descripcion,tipo_inmueble,tipo_servicio,precio,codigo_arrendador) values ("2","3","si","no","ninguna","apartamento","1","1100000","12");
insert into inmueble(baños,habitaciones,patio,garaje,descripcion,tipo_inmueble,tipo_servicio,precio,codigo_arrendador) values ("2","5","si","si","ninguna","casa","2","1200000","17");
insert into inmueble(baños,habitaciones,patio,garaje,descripcion,tipo_inmueble,tipo_servicio,precio,codigo_arrendador) values ("2","3","si","no","ninguna","apartamento","1","1300000","15");
insert into inmueble(baños,habitaciones,patio,garaje,descripcion,tipo_inmueble,tipo_servicio,precio,codigo_arrendador) values ("2","3","si","no","ninguna","apartamento","1","1000000","12");
insert into inmueble(baños,habitaciones,patio,garaje,descripcion,tipo_inmueble,tipo_servicio,precio,codigo_arrendador) values ("2","4","si","no","ninguna","apartamento","2","1500000","17");
insert into inmueble(baños,habitaciones,patio,garaje,descripcion,tipo_inmueble,tipo_servicio,precio,codigo_arrendador) values ("2","3","si","no","ninguna","apartamento","1","900000","12");
insert into inmueble(baños,habitaciones,patio,garaje,descripcion,tipo_inmueble,tipo_servicio,precio,codigo_arrendador) values ("2","3","si","no","ninguna","casa","1","900000","19");
insert into inmueble(baños,habitaciones,patio,garaje,descripcion,tipo_inmueble,tipo_servicio,precio,codigo_arrendador) values ("2","3","si","si","ninguna","apartamento","2","900000","18");
insert into inmueble(baños,habitaciones,patio,garaje,descripcion,tipo_inmueble,tipo_servicio,precio,codigo_arrendador) values ("2","3","si","no","ninguna","casa","1","900000","13");
insert into inmueble(baños,habitaciones,patio,garaje,descripcion,tipo_inmueble,tipo_servicio,precio,codigo_arrendador) values ("2","3","no","si","ninguna","local","1","900000","20");
