use cebercol;
select * from personas;
insert into personas(nombre, correo, telefeno, direccion, rol) values ("juan","j1@gmail.com","3204991618","recreo","arriendatario");
insert into personas(nombre, correo, telefeno, direccion, rol) values ("jose","j2@gmail.com","3204991619","galan","arriendatario");
insert into personas(nombre, correo, telefeno, direccion, rol) values ("jair","j3@gmail.com","3204991617","recreo","arriendatario");
insert into personas(nombre, correo, telefeno, direccion, rol) values ("jimena","j4@gmail.com","3204991616","colombia","arriendatario");
insert into personas(nombre, correo, telefeno, direccion, rol) values ("jacinto","j5@gmail.com","3204991615","galan","arriendatario");
insert into personas(nombre, correo, telefeno, direccion, rol) values ("alvaro","j6@gmail.com","3204991614","recreo","arriendatario");
insert into personas(nombre, correo, telefeno, direccion, rol) values ("aldair","j7@gmail.com","3204991613","palmira","arriendatario");
insert into personas(nombre, correo, telefeno, direccion, rol) values ("maria","j8@gmail.com","3204991612","recreo","arriendatario");
insert into personas(nombre, correo, telefeno, direccion, rol) values ("mariana","j9@gmail.com","3204991611","palmira","arriendatario");
insert into personas(nombre, correo, telefeno, direccion, rol) values ("mariela","j10@gmail.com","3204991628","colombia","arriendatario");
insert into personas(nombre, correo, telefeno, direccion, rol) values ("ana","j11@gmail.com","3204991638","recreo","arriendatario");
insert into personas(nombre, correo, telefeno, direccion, rol) values ("karen","j12@gmail.com","3204991648","palmira","arrendador");
insert into personas(nombre, correo, telefeno, direccion, rol) values ("claudia","j13@gmail.com","3204991658","recreo","arrendador");
insert into personas(nombre, correo, telefeno, direccion, rol) values ("jehovana","j14@gmail.com","3204991668","recreo","arrendador");
insert into personas(nombre, correo, telefeno, direccion, rol) values ("felipe","j15@gmail.com","3204991678","palmira","arrendador");
insert into personas(nombre, correo, telefeno, direccion, rol) values ("julian","j16@gmail.com","3204991688","colombia","arrendador");
insert into personas(nombre, correo, telefeno, direccion, rol) values ("omar","j17@gmail.com","3204991318","recreo","arrendador");
insert into personas(nombre, correo, telefeno, direccion, rol) values ("yonatan","j18@gmail.com","3204991418","colombia","arrendador");
insert into personas(nombre, correo, telefeno, direccion, rol) values ("jorge","j19@gmail.com","3204991518","recreo","arrendador");
insert into personas(nombre, correo, telefeno, direccion, rol) values ("kevin","j20@gmail.com","3204991118","rosario","arrendador");